### ISSUE TITLE
Problems running the example

### ISSUE THREAD

**Issue by alexd1971** [angel-example/gallery#1]
When pub serve:
```
$ pub serve
Loading source assets... 
Loading angel_configuration, angular2 and dart_to_js_script_rewriter transformers... (2.4s)
Serving angel web  on http://localhost:8080
Serving angel test on http://localhost:8081
Build completed successfully
```
When dart bin/server.dart:
```
$ dart bin/server.dart 
Unhandled error occurred: Exception: If you specify a type for MongoService, it must extend Model.
#0      new MongoTypedService (package:angel_mongo/mongo_service_typed.dart:10:7)
#1      configureServer.<anonymous closure> (package:angel/src/services/artist.dart:9:33)
<asynchronous suspension>
#2      Angel.configure (package:angel_framework/src/http/server.dart:515:21)
<asynchronous suspension>
#3      configureServer (package:angel/src/services/services.dart:13:13)
<asynchronous suspension>
#4      Angel.configure (package:angel_framework/src/http/server.dart:515:21)
<asynchronous suspension>
#5      createServer (package:angel/angel.dart:15:13)
<asynchronous suspension>
#6      startServer (file:///Users/aleksd/projects/test/angel/gallery/bin/server.dart:13:19)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1120)
#8      _CustomZone.run (dart:async/zone.dart:1001)
#9      _CustomZone.runGuarded (dart:async/zone.dart:901)
#10     runZoned (dart:async/zone.dart:1465)
#11     main (file:///Users/aleksd/projects/test/angel/gallery/bin/server.dart:9:3)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by thosakwe** [comment]
Sorry for the inconvenience; this is an old example, from 8 months ago, which was before Angel was even officially in alpha. Thus, some of the API's used are now deprecated, such as `MongoTypedService`.

For a current example of Angel and Angular2 together, check out: https://github.com/angel-example/with_angular2.

I'm going to mark this repo as defunct (it was never finished, anyways), and point people to the `with_angular2` example instead.

**Comment by thosakwe** [comment]
Note to self: from now on, include a `pubspec.lock` in example projects.
